name: C/C++ CI

on:
  push:
    branches: [ main, v0.5 ]
  pull_request:
    branches: [ main, v0.5 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v4
    - name: log untrusted output
      run: |
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        echo "untrusted output"
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'
    - name: make
      run: make
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python tools/xiaotea/Scripts/prepareZip_online.py
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: M365_v3_build_${{ github.run_number }}
        retention-days: 5
